### PR TITLE
allows for props to dynamically update animate-able data

### PR DESCRIPTION
**Pull request by sankho**
using this on a project I'm working on
- saves the d3 datamap in memory to the react component class so it can be re-used if needed
- allows for prop changes on bubbles or data to be animated
- adds prop for `reset` option on data updates using `updateChloropeth`
- redraws map on height or width changes as these can't be done w/n the existing datamap

### CODE REVIEW

**Comment by btmills** [comment]
@sankho thanks for this! I was able to take what you did here and combine it with a rewrite of the examples in #2 so that I can demonstrate parity with the examples at https://datamaps.github.io. Can you check out the [`src/datamaps.jsx` changes](https://github.com/btmills/react-datamaps/pull/2/files#diff-f337244ccdc1b1d91a258902b3bbd702) in #2 and let me know what you think?

I didn't include the `resetOnUpdateChoropleth` option in #2 yet. What does the `reset` option do there?

**Comment by sankho** [comment]
@btmills the update branch looks great, like the transition to using the ES6 class approach as opposed to the old ES5 approach.

`resetOnUpdateChoropleth`, or as you say the `reset` option on the datamaps' `updateChoropleth` method - resets the map of all data when you call `updateChoropleth`. So if it's set to `true`, the updating data will overwrite the previous dataset, where if it's set to `false`, it will be additive / merged in w/ the old dataset.

Would love to build on top ofyour changes - I pushed a few more changes to my branch to deal with a few bugs I caused but it's all in the old React component form, would like to move on to the latest. LMK if you merge it in and I can make another PR!

**Comment by btmills** [comment]
@sankho thanks for the explanation! I added an `updateChoroplethOptions` prop in 4b6acf3ea037bf8ed79e5c6a4e9994fd1ca98b92. The [datamaps v0.4.4 release notes](https://github.com/markmarkoh/datamaps/releases/tag/v0.4.4) said `reset` is the only key it cares about now, but having users pass in `updateChoroplethOptions={{ reset: true }}` makes it forward-compatible without any updates here if there are other options added later.

I just merged #2, so you should be good to start building on top of it (and sorry about the merge conflicts 😳 ).

**Comment by sankho** [comment]
@btmills actually the changes you made in #2 satisfy my needs. Gonna move onto solving issue #3 next.

Examples page looks great btw!

**Pull request closed without merging**
